config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :users, only: [:new, :create, :show, :delete] do 
    resources :recipes, only: [:index]
    resources :makings, shallow: true
  end

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete "/signout", to: "sessions#destroy"

  resources :ingredients

  resources :recipes

  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/signin')

  get '/makings' => 'makings#index'

  post '/makingsFromRecipe', to: 'makings#createFromRecipe'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :amounts
  has_many :recipes, :through => :amounts

  validates :name, :serving_size_number, :serving_size_unit, presence: true
  validates :name, uniqueness: true 


  def name_with_serving_info
    "#{self.name} #{self.serving_size_number} #{self.serving_size_unit}"
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :find_ingredient_by_params_id, only: [:update, :destroy, :edit, :show]

  def index
    @ingredients = Ingredient.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @ingredients, status: 200}
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredients_params)
    if @ingredient.save
      redirect_to ingredient_path(@ingredient)
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end


  def update
    @ingredient.update(ingredients_params)
    if @ingredient.save
      #maybe add success message
      redirect_to "/ingredients/#{@ingredient.id}"
    else
      render "edit"
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to "/ingredients"
  end

  private

  def find_ingredient_by_params_id
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredients_params
    params.require(:ingredient).permit(:name, :serving_size_number, :serving_size_unit)
  end
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if f.object.errors.any? %>
    <% f.object.errors.full_messages.each do |message|%>
      <%= message %><br>
    <%end%>
    <br>
  <%end%>
  
  <%=f.label :name%>
  <%= f.text_field :name, class: "form_fields"%><br>
  <%= f.label :serving_size_number, "Serving Size"%>
  <div class="form_fields">
    <%= f.number_field :serving_size_number, placeholder: "number (e.g. 3)"%> <%= f.text_field :serving_size_unit, placeholder: "unit (e.g. cup)"%>
  </div><!--form-fields-->
  <br>
  <br>
  <%= f.submit :class => "submit_class" %>
<%end%>

app/views/ingredients/edit.html.erb
<div id="ingredients-edit">
  <div class="body-title">
    <h1>Edit <%=@ingredient.name%></h1>
  </div><!--title-->
    <%= render 'form' %>
</div><!--ingredients-edit-->

app/views/ingredients/index.html.erb
<h1 class="body-title">Ingredients</h1>

<div id="ingredients-index-buttons">
  
  <button id="previous">Previous</button>
  
  <button id="next">Next</button>

</div>

<div class="ingredients">
  
  <div id="ingredients-index">

  </div>

</div>

<script>
  getIngredients();
</script>

app/views/ingredients/new.html.erb
<div id="ingredients-new">
  <h1 class="body-title">Save an Ingredient</h1>
  <div class="from-holder">
    <%= render 'form' %>
  </div>
</div><!--ingredients-new-->

app/views/ingredients/show.html.erb
<div id="ingredients-show">
  <h1 class="body-title"><%=@ingredient.name%></h1>

  <div class="serving">
    Serving Size: <%="#{@ingredient.serving_size_number} #{@ingredient.serving_size_unit}"%>
  </div><!--serving-->

  <div class="edit_delete">
    
    <div class="edit block">
      <%=link_to "Edit Ingredient", edit_ingredient_path(@ingredient) %>
    </div><!--edit-->

    <div class="delete block">
      <%=link_to "Delete Ingredient", ingredient_path(@ingredient), method: :delete %>
    </div><!--delete-->

  </div><!--edit_delete-->

</div><!--ingredients-show-->