config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resources :users, only: [:new, :create, :show, :delete] do 
    resources :recipes, only: [:index]
    resources :makings, shallow: true
  end

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete "/signout", to: "sessions#destroy"

  resources :ingredients

  resources :recipes

  get '/auth/facebook/callback' => 'sessions#create'
  get 'auth/failure', to: redirect('/signin')

  get '/makings' => 'makings#index'

  post '/makingsFromRecipe', to: 'makings#createFromRecipe'
end

app/models/making.rb
class Making < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  scope :latest, -> { order(created_at: :desc) }
  scope :five, -> { limit(5) }

end

app/controllers/makings_controller.rb
class MakingsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :find_making_by_params_id, only: [:update, :destroy, :edit, :show]
  before_action :redirect_if_making_belongs_to_another_user, only: [:update, :destroy, :edit]

  def index
    if params[:user_id]
      @makings = User.find(params[:user_id]).makings
    else
      @makings = Making.all
    end
  end

  def show
  end

  def new
    @user = current_user
    @making = @user.makings.build
  end

  def create
    @making = Making.new(makings_params)
    @making.user = User.find(params[:user_id])
    if @making.save
      redirect_to "/makings/#{@making.id}"
    else
      render "new"
    end
  end

  def createFromRecipe
    @making = Making.new(makings_params)
    @making.user = current_user
    if @making.save
      render json: @making, status: 200
    end
  end

  def edit
  end

  def update
    @making.update(makings_params)
    if @making.save
      redirect_to "/makings/#{@making.id}"
    else
      render "edit"
    end
  end

  def destroy
    @making.destroy
    redirect_to "/users/#{current_user.id}"
  end

  private 

  def makings_params
    params.require(:making).permit(:recipe_id, :rating, :notes)
  end

  def find_making_by_params_id
    @making = Making.find(params[:id])
  end

end

app/helpers/makings_helper.rb
module MakingsHelper
  
  def five_most_recent_recipes
    Making.latest.five
  end


end

app/views/makings/_display_makings.erb
<div class="main">
  <ol>
    <%makings.each do |m|%>
      <li>
        <%=link_to m.recipe.name, making_path(m)%>
      </li>
    <%end%>
  </ol>
</div><!--main-->

app/views/makings/_display_makings_for_users_show.html.erb
<div class="main">
  <ol>
    <%makings.each do |m|%>
      <li>
        <%=link_to m.recipe.name, making_path(m)%>
      </li>
    <%end%>
  </ol>
</div><!--main-->

app/views/makings/_edit_form.html.erb
<%=form_for(@making)do |f|%>
  <% if f.object.errors.any? %>
    <% f.object.errors.full_messages.each do |message|%>
      <%= message %><br>
    <%end%>
    <br>
  <%end%>

  <%= f.label :recipe%>
  <%= f.collection_select :recipe_id, Recipe.all, :id, :name %>
  <%= f.label :rating%>
  <%= f.number_field :rating, class: "form_fields"%>
  <%= f.label :notes%>
  <%= f.text_field :notes, class: "form_fields"%>

  
  <br>
  <br>
  <br>
  <br>
  <%=f.submit :class => "submit_class"%>
<%end%>

app/views/makings/_form.html.erb
<%=form_for([@user, @making])do |f|%>
  <% if f.object.errors.any? %>
    <% f.object.errors.full_messages.each do |message|%>
      <%= message %><br>
    <%end%>
    <br>
  <%end%>

    <%= f.label :recipe%>
    <%= f.collection_select :recipe_id, Recipe.all, :id, :name%>
    <%= f.label :rating%>
    <%= f.number_field :rating, class: "form_fields"%>
    <%= f.label :notes%>
    <%= f.text_field :notes, class: "form_fields"%>
    <br>
    <br>
    <br>
    <br>

  <%=f.submit :class => "submit_class"%>
<%end%> 

app/views/makings/edit.html.erb
<h1 class="recipes-page-with-form">Edit Making</h1>
<%= render 'edit_form' %>

app/views/makings/index.html.erb
<h1 class="body-title">Makings</h1>

<div class="makings">
  <%@makings.each do |m|%>
      <div class="name">
        <%=link_to m.recipe.name, making_path(m)%>
      </div><!--name-->
      <div class="info">
        Made by: <%=m.user.name%><br>
        Rating:<%=m.rating%> stars <br>
        Notes:<br>
        <%=m.notes%><br>
      </div><!--serving-->
  <%end%>
</div><!--makings-->

app/views/makings/new.html.erb
<div id="makings-new">
  <h1 class="body-title">What'd you make?</h1>
    <%= render 'form' %>
</div><!--makings-new-->

app/views/makings/show.html.erb
<div id="makings-show">
  <h1 class="body-title"><%=@making.user.name%> made <%=link_to @making.recipe.name, recipe_path(@making.recipe)%></h1>
    

  <div class="info block">
    Rating:  <%=@making.rating%> stars <br>
    Notes:<br>
    <%=@making.notes%><br>
  </div><!--info-->

  <div class="edit_delete">
    
    <div class="edit block">
      <%=link_to "Edit Making", edit_making_path(@making) %>
    </div><!--edit-->

    <div class="delete block">
      <%=link_to "Delete Making", making_path(@making), method: :delete %>
    </div><!--delete-->

  </div><!--edit_delete-->
</div><!--makings-show-->